t = ('a','s','d','f')
print(t)
print(t[0])
print(t[-1])
print(t[1:-1])
for c in t:
    print(c)
print('a' in t)
print('b' in t)
print(t.index('d'))
print(t.count('a'))
print(t.count('b'))
print(len(t))
t2 = ('z','x','z')
print(t2)
print(t2.count('z'))