string = 'ABCDE'
print('String:')
print(string)
print('Third character (index 2):')
print(string[2])
print('String length:')
print(len(string))
print('Substring since index 2:')
print(string[2:])
print('Substring until index 2:')
print(string[:2])
print('Last char (index -1):')
print(string[-1])
print('Three last chars (since index -3):')
print(string[-3:])