print(True)
print(False)
print('------------------')
print(not True)
print(not False)
print('------------------')
print(False and False)
print(False and True)
print(True and False)
print(True and True)
print('------------------')
print(False or False)
print(False or True)
print(True or False)
print(True or True)
print('------------------')